FORMAT: 1A
HOST: http://localhost:8000/server/api

# KotsApp API
This an API documentation of our web application.

## Website
https://kotsapp.herokuapp.com/home

# Group Models

> List of models in the PostgreSQL database

## <i class="fa fa-users"></i> Users
 ::: note
* Users model/table in the PostgreSQL database
 :::

    + Schema
    
      <!-- include(./models/users-schema.json) -->


<!-- include(./models-blueprint/users/users.apib) -->






