name: Continuous Integration
on: 
  push:
    branches:
      - master

env:
  node-version: 14.15.1
      
jobs:
  test-frontend:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Setup Node ${{ env.node-version }}
          uses: actions/setup-node@v1
          with:
            node-version: ${{ env.node-version }}
        - name: npm install
          working-directory: ./client-side
          run: |
            npm install
        - name: run tests
          working-directory: ./client-side
          run: |
            npm run test-headless
  
  test-backend:
      runs-on: ubuntu-latest
      env: 
        JWT_KEY: qR7AAJGnR8CorNYVBfslYQ

      services:
        postgres:
          image: postgres:12
          env:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: kots_test
          ports:
            - 5432:5432
          options: >-
            --health-cmd pg_isready
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5
      steps:
        - uses: actions/checkout@v2
        - name: Setup Node ${{ env.node-version }}
          uses: actions/setup-node@v1
          with:
            node-version: ${{ env.node-version }}
        - name: npm install
          working-directory: ./
          run: |
            npm install
        - name: run tests (integration & unit tests)
          working-directory: ./
          run: |
            npm run test:all

  build-to-Heroku:
    runs-on: ubuntu-latest
    needs: [test-frontend, test-backend]
    steps:
      - uses: actions/checkout@v2
      - name: Node ${{ env.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.node-version }}

      - name: npm install
        working-directory: ./
        run: |
          npm install
          cd ./client-side && npm install

      - name: build frontend
        working-directory: ./client-side
        run: |
          npm run build
          
      - name: Commit changes
        working-directory: ./
        run: |
          rm .env.dev
          git add -A
          git commit -m "passed backend tests & successful build !"
    
      - uses: akhileshns/heroku-deploy@v3.3.6
        if: ${{ always() }}
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
        env:
          NODE_ENV: "production"
          JWT_KEY: ${{secrets.JWT_KEY}}
          NPM_CONFIG_PRODUCTION: "false"
